### ISSUE TITLE
make_corpus.py doesn't work

### ISSUE THREAD

**Issue by cyclone-joker** [rknaebel/bbc-discourse#1]
How do you do bro?
I would like to use your corpus to train my model with explicit discourse relation task，but your code have something wrong on make corpus.py  by:
corpus, topic, id = path.split('/')[-3:]
the raw text doesn't have 3 vals.

**Comment by rknaebel** [comment]
Hey there,
the three vals should refer to the path structure of the unzipped dataset.
After downloading the reference datasets and uncompressing them both to some path CORPUS_PATH, the folder structure should be similar to: 
**CORPUS_PATH/CORPUS/TOPIC/ID**

*_Depending on your plans, please remember that those explicit relations are automatically extracted by a model trained on PDTBv2._

**Comment by cyclone-joker** [comment]
Thank you for your answer，and I found it‘s my fault.
The "/" can be used in linux and "\\" may be right on windows.
ps: (requirements.txt i think it's necessary because it's really hard to be fit with the package version like spacy and nltk)
